// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// extractAlleleCounts
void extractAlleleCounts(CharacterMatrix fmt, CharacterMatrix dat, NumericMatrix ref, NumericMatrix alt);
RcppExport SEXP _GUSbase_extractAlleleCounts(SEXP fmtSEXP, SEXP datSEXP, SEXP refSEXP, SEXP altSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type fmt(fmtSEXP);
    Rcpp::traits::input_parameter< CharacterMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ref(refSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alt(altSEXP);
    extractAlleleCounts(fmt, dat, ref, alt);
    return R_NilValue;
END_RCPP
}
