# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extractAlleleCounts <- function(fmt, dat, ref, alt) {
    invisible(.Call(`_GUSbase_extractAlleleCounts`, fmt, dat, ref, alt))
}

